### ISSUE TITLE
Query about node encoding

### ISSUE THREAD

**Issue by MahirGulzar** [sancarlim/Explainable-MP#2]
Hi @sancarlim ,

Great to see an extension of PGP. This may be a naive question but I wanted to ask that in both PGP and your paper the graph nodes are encoded using GRUs. I understand the point of capturing temporal features of target and surrounding agents using them but why graph nodes are encoded using GRUs? The way I understand it is that graph nodes are static where each node consists of a fixed number of poses. The scene moves forward and graph nodes move back in time other than this what else do we encode for them?

Thanks.

**Comment by sancarlim** [comment]
Thank you for your question @MahirGulzar .
By graph nodes, I understand you are referring to lane graph nodes. You are correct in that they are static in the sense that they do not move within a single frame. However, the order and connectivity of the nodes can change across frames.
By encoding the lane graph nodes using GRUs, we can capture the temporal dependencies between nodes across frames. 
Additionally, the lane graph itself is a dynamic structure that can change over time, for example, due to lane merges or splits. By using GRUs to encode the lane graph nodes, we can capture these changes and update our predictions accordingly.

I hope this helps clarifies your question :)
